runtime: nodejs20
service: default

env_variables:
  NODE_ENV: "production"
  DATABASE_URL: "postgres://postgres:ssdfg69420@/pasteshare?host=/cloudsql/coastal-bloom-460014-j6:asia-south1:pasteshare-db"

handlers:
  # Serve API requests
  - url: /api/.*
    script: auto
    secure: always
  
  # Serve static files
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))
    static_files: client/build/\1
    upload: client/build/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)
    secure: always

  # All other requests are routed to index.html
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html
    secure: always

beta_settings:
  cloud_sql_instances: coastal-bloom-460014-j6:asia-south1:pasteshare-db

automatic_scaling:
  max_instances: 2
  min_instances: 0 