version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://pasteshare:pasteshare@postgres:5432/pasteshare
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=pasteshare
      - POSTGRES_PASSWORD=pasteshare
      - POSTGRES_DB=pasteshare
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  pasteshare_uploads:
    # This ensures uploaded files persist across container restarts 