version: '3.8'

services:
  # Backend Server with hot-reload - using Supabase database
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    container_name: pasteshare-server-dev
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
      DATABASE_URL: ${DATABASE_URL}
      UPLOAD_DIR: ${UPLOAD_DIR:-/app/uploads}
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/app/server/src
      - ./api:/app/api
      - uploads_dev_data:/app/uploads
    networks:
      - pasteshare-dev-network
    restart: unless-stopped
    command: npm run dev

  # Frontend Client with hot-reload
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: pasteshare-client-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    networks:
      - pasteshare-dev-network
    depends_on:
      - server
    restart: unless-stopped

volumes:
  uploads_dev_data:

networks:
  pasteshare-dev-network:
    driver: bridge 