runtime: nodejs20
service: api

env_variables:
  NODE_ENV: "production"
  # Cloud SQL connection using unix socket
  DATABASE_URL: "postgres://postgres:ssdfg69420@/pasteshare?host=/cloudsql/coastal-bloom-460014-j6:asia-south1:pasteshare-db"

handlers:
  - url: /.*
    script: auto
    secure: always

beta_settings:
  cloud_sql_instances: coastal-bloom-460014-j6:asia-south1:pasteshare-db 